---
# tasks file for task03-deploy
- name: ocp4-deploy | task03-deploy | Create ssh config
  include_tasks: create-ssh-config.yml
- name: ocp4-deploy | task03-deploy | registry-pre-init
  include_tasks: registry-pre-init.yml
