---
####### Clone Git Dependencies
- name: '{{ ansible_name_module }} | role | stat | find ansible .git'
  stat:
    path: '{{ dir_git_mirror }}/.git'  
  register: dir_git_mirror_check

- name: '{{ ansible_name_module }} | role | Clone Git Dependencies' 
  when: dir_git_mirror_check.stat.exists == False
  git:
    clone: yes
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ git_branch }}"
    key_file: "{{ sshkeys_priv_file }}"
  with_items:
    - "{{ gitrepos }}"

# name: ocp4-deploy | task02-ignition | Initilize terraform modules
# shell: "cd {{ item }} && terraform init"
# with_items:
#   - "{{ dir_one }}/terraform/aws-platform-base/"
#   - "{{ dir_one }}/terraform/aws-platform-openshift4-registry/"
#   - "{{ dir_one }}/terraform/aws-platform-openshift4-bootstrap/"
#   - "{{ dir_one }}/terraform/aws-platform-openshift4-masters/"
