---
####### Set AWS GovCloud Credentials
- name: '{{ ansible_name_module }} | copy | Place AWS Credentials'
  copy:
    src: "{{ dir_secrets }}/aws/credentials"
    dest: "{{ local_home }}/.aws/credentials"

