---
- name: '{{ ansible_name_module }} | command:htpasswd.bcrypt | Generate Default Registry Basic Auth'
  command:
    cmd: 'htpasswd -Bbn {{ reg_name_user }} {{ reg_user_pass }}'
  register: bcrypt_htpasswd

- name: '{{ ansible_name_module }} | copy:content.bcrypt_htpasswd | Generate Default Registry Basic Auth'
  copy:
    content: '{{ bcrypt_htpasswd.stdout }}'
    dest: /root/deploy/secrets/registry/auth/htpasswd

# Disabled due to no docker registry compatibile bcrypt algo
# name: '{{ ansible_name_module }} | htpasswd | Generate Default Registry Basic Auth'
# htpasswd:
#   path: "{{ dir_deploy }}/secrets/registry/auth/htpasswd"
#   name: cloudctl
#   password: cloudctl
