---
- name: ocp4-deploy | task03-deploy | Create docker config directory
  file:
    path: "{{ home_directory }}/.docker"
    state: directory

- name: ocp4-deploy | task03-deploy | Copy credentials to directory
  copy:
    src: "{{ artifact_directory }}/.docker/master.json"
    dest: "{{ home_directory }}/.docker/config.json"

- name: ocp4-deploy | task03-deploy | Download PpenShift images for registry
  block:
    - name: ocp4-deploy | task03-deploy | Check for file existence
      find:
        file_type: directory
        paths: "{{ base_directory }}/mirror"
      register: files

    - name: ocp4-deploy | task03-deploy | Remove any existing directories (if they exist)
      file:
        path: "{{ base_directory }}/mirror"
        state: absent
      when: files.examined > 0 

    - name: ocp4-deploy | task03-deploy | Create registry mirror directory
      file:
        path: "{{ base_directory }}/mirror"
        state: present

    - name: ocp4-deploy | task03-deploy | Create task03-deploy mirror directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "{{ base_directory }}/mirror"
        - "{{ home_directory }}/.docker"

    - name: ocp4-deploy | task03-deploy | Sync content from quay.io
      shell: |
        oc adm release mirror \
        --from=quay.io/openshift-release-dev/ocp-release:{{ ocp_version }}-x86_64 \
        --to-dir={{ base_directory }}/mirror

# Rescue block if there are any failures in the above block
  rescue:
    - name: ocp4-deploy | task03-deploy | Remove any existing directories (if they exist)
      file:
        path: "{{ base_directory }}/mirror"
        state: absent

    - name: ocp4-deploy | task03-deploy | Create registry mirror directory
      file:
        path: "{{ base_directory }}/mirror"
        state: present

    - name: ocp4-deploy | task03-deploy | Sync content from quay.io
      shell: |
        oc adm release mirror \
        --from=quay.io/openshift-release-dev/ocp-release:{{ ocp_version }}-x86_64 \
        --to-dir={{ base_directory }}/mirror
      register: mirror

# This tarball is used in the next task for uploading images to container registry
- name: ocp4-deploy | task03-deploy | Archive images and artifacts
  command:
    "tar -cvzf {{ home_directory }}/PlatformOne.tar.gz \
     -C {{ home_directory }} PlatformOne"
  args:
    creates: "{{ home_directory }}/PlatformOne.tar.gz"
