#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: 'RedHat | PlatformOne | deploy | hydrate' 
  hosts: containerone
  vars_files:
    - '../p1.yml'
    - 'vars/{{ target_environment }}.yml'
    - 'vars/global.yml'
  vars:
    module: "hydrate"
    ansible_name_module: "{{ ansible_name }} | deploy | {{ module }}"
  tasks:
          - name: '{{ ansible_name_module }} | shell:oc.image.mirror | Load images from file into registry.{{ cluster_domain }}' 
      shell: |
        oc image mirror \
          -a {{ dir_artifacts }}/.docker/mirror.json \
          --dir={{ local_home }}/PlatformOne/mirror \
          file://openshift/release:{{ version_openshift }}* \
          registry.{{ cluster_domain }}:5000/ocp-{{ version_openshift }}
