#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: '{{ ansible_name }} | deploy | ignition' 
  hosts: localhost
  connection: local
  vars:
    module: "ignition"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  vars_files:
    - variables
    - aux/vars/repos.yml
    - aux/vars/{{ target_environment }}.yml
  roles:
    - ignition
