#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: 'RedHat | PlatformOne | deploy | hydrate' 
  hosts: localhost
  vars_files:
    - '../p1.yml'
    - 'vars/{{ target_environment }}.yml'
    - 'vars/global.yml'
  vars:
    module: "local"
    ansible_name_module: "{{ ansible_name }} | deploy | {{ module }}"
  tasks:

    - name: '{{ ansible_name_module }} | copy | Load AWS Credentials ~/.aws/credentials' 
      copy:
        src: '{{ dir_artifacts }}/.aws/govcloud.credentials'
        dest: '{{ local_home }}/.aws/credentials'

    - name: '{{ ansible_name_module }} | copy | Load Docker Registry ~/.docker/config.json' 
      copy:
        src: '{{ dir_artifacts }}/.docker/mirror.json'
        dest: '{{ local_home }}/.docker/config.json'

    - name: '{{ ansible_name_module }} | copy | Copy Docker Registry Mirror Certificate to /etc/pki/ca-trust/source/anchors/{{ cluster_domain }}.crt' 
      become: true
      become_user: root
      copy:
        src: '{{ dir_artifacts }}/ssl/{{ cluster_domain }}.crt'
        dest: '/etc/pki/ca-trust/source/anchors/{{ cluster_domain }}.crt'

    - name: '{{ ansible_name_module }} | shell:update-ca-trust | Load New Certificate'
      become: true
      become_user: root
      shell: |
        update-ca-trust

