#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: 'RedHat | PlatformOne | deploy' 
  hosts: containerone

# import_playbook: bootstrap.yml                 # Launch Bootstrap Instance
# import_playbook: masters.yml                   # Launch Master Instances
# import_playbook: monitor.yml                   # Monitor cluster up status
