#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: '{{ ansible_name }} | bundle | template' 
  hosts: localhost
  connection: local
  vars:
    module: "template"
    ansible_name_module: "{{ ansible_name }} | bundle | {{ module }}"
    dir_deploy_templates: "{{ dir_git_deploy }}/templates"
    tmpl_installconfig_j2: "{{ dir_deploy_templates }}/openshift-install/{{ cloud_provider }}-{{ target_environment }}-install-config.yaml.j2"
  vars_files:
    - 'variables'
    - 'vars/repos.yml'
    - 'vars/{{ target_environment }}.yml'
  tasks:
    - name: '{{ ansible_name_module }} | template' 
      template:
        src: '{{ tmpl_installconfig_j2 }}'
        dest: '{{ dir_artifacts }}/data/install-config.yaml'
