#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: '{{ ansible_name }} | bundle | template' 
  hosts: localhost
  connection: local
  vars:
    module: "template"
    cloud_provider: "aws"
    ansible_name_module: "{{ ansible_name }} | bundle | {{ module }}"
    dir_deploy_templates: "{{ dir_git_deploy }}/templates"
    tmpl_installconfig_j2: "{{ dir_deploy_templates }}/openshift-install/{{ cloud_provider }}-{{ target_environment }}-install-config.yaml.j2"
    cloud_key_id_special: "{{ lookup('ini', 'aws_access_key_id section=default file={{ dir_artifacts }}/.aws/govcloud.credentials') }}"
    cloud_key_secret_special: "{{ lookup('ini', 'aws_secret_access_key section=default file={{ dir_artifacts }}/.aws/govcloud.credentials') }}"
    redhat_quay_pull_file: '{{ dir_artifacts }}/.docker/master.json }}'
  vars_files:
    - 'variables'
    - 'p1.yml'
    - 'vars/repos.yml'
    - 'vars/{{ target_environment }}.yml'
  tasks:
    - name: '{{ ansible_name_module }} | template | openshift-install.yaml' 
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      loop: 
        - { mode: '755', src: "{{ tmpl_installconfig_j2 }}", dest: "{{ dir_artifacts }}/data/install-config.yaml" }
        - { mode: '755', src: "{{ dir_deploy_templates }}/openshift-install/99_openshift-image-registry_installer-cloud-credentials-secret.yaml.j2", dest: "{{ dir_artifacts }}/bak/openshift/99_openshift-image-registry_installer-cloud-credentials-secret.yaml"}
        - { mode: '755', src: "{{ dir_deploy_templates }}/openshift-install/99_openshift-ingress-operator_cloud-credentials-secret.yaml.j2", dest: "{{ dir_artifacts }}/bak/openshift/99_openshift-ingress-operator_cloud-credentials-secret.yaml"}
        - { mode: '755', src: "{{ dir_deploy_templates }}/openshift-install/99_openshift-machine-api_aws-cloud-credentials-secret.yaml.j2", dest: "{{ dir_artifacts }}/bak/openshift/99_openshift-machine-api_aws-cloud-credentials-secret.yaml"}
