#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: '{{ ansible_name }} | bundle | prep' 
  hosts: localhost
  connection: local
  vars:
    name_bucket: 'the-fence'
    module: "upload"
    ansible_name_module: "{{ ansible_name }} | bundle | {{ module }}"
    cloud_key_id_special: "{{ lookup('ini', 'aws_access_key_id section=default file={{ dir_artifacts }}/.aws/govcloud.credentials') }}"
    cloud_key_secret_special: "{{ lookup('ini', 'aws_secret_access_key section=default file={{ dir_artifacts }}/.aws/govcloud.credentials') }}"
  vars_files:
    - 'p1.yml'
    - 'variables'
    - 'vars/repos.yml'
    - 'vars/seed.yml'
    - 'vars/{{ target_environment }}.yml'
  tasks:

#   - name: '{{ ansible_name_module }} | aws_s3 | Create AWS S3 Bucket: {{ name_cluster_vpc }}' 
#     aws_s3:
#       bucket: '{{ name_cluster_vpc }}'
#       region: '{{ cloud_region }}'
#       mode: create
#       aws_access_key: '{{ cloud_key_id_special }}'
#       aws_secret_key: '{{ cloud_key_secret_special }}'

    - name: '{{ ansible_name_module }} | aws_s3 | Push Bundle to AWS S3 Bucket: {{ name_bucket }}' 
      aws_s3:
        mode: put
        bucket: '{{ name_bucket }}'
        object: 'PlatformOne.tar.gz'
        src: '{{ dir_one }}/PlatformOne.tar.gz'
        aws_access_key: '{{ cloud_key_id_special }}'
        aws_secret_key: '{{ cloud_key_secret_special }}'

