#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: 'RedHat | PlatformOne | bundle | vars' 
  hosts: localhost
  connection: local
  vars:
    module: "vars"
    git_branch: master
    cloud_provider: "aws"
    cloud_region: "us-gov-west-1"
    ansible_name: 'RedHat | PlatformOne'
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
    dir_one: "{{ lookup('env', 'HOME')  }}/PlatformOne"
    dir_artifacts: "{{ lookup('env', 'p1DirArtifacts')  }}"
    ansible_varsj2: '{{ dir_one }}/ansible/deploy/templates/ansible/variables.j2'
    cluster_domain: "{{ lookup('env', 'p1ClusterDomain')  }}"
    redhat_quay_pull_file: '{{ dir_artifacts }}/.docker/master.json }}'
  vars_files:
    - p1.yml
    - vars/seed.yml
  tasks:
    - name: '{{ ansible_name_module }} | bundle | stage variables file' 
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      with_items:
        - { src: '{{ ansible_varsj2 }}', dest: '{{ dir_deploy }}/variables' }
        - { src: '{{ dir_artifacts }}/environment', dest: '/etc/profile.d/one.env' }
