#!/usr/local/bin/ansible-playbook
- name: 'RedHat | PlatformOne | bundle | vars' 
  hosts: localhost
  connection: local
  vars:
    module: "vars"
    git_branch: master
    cloud_region: "us-gov-west-1"
    ansible_name: 'RedHat | PlatformOne'
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  vars_files:
    - vars/seed.yml
  tasks:
    - name: '{{ ansible_name_module }} | bundle | stage variables file' 
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
      with_items:
        - { src: '{{ ansible_varsj2 }}', dest: '{{ dir_deploy }}/variables' }
        - { src: '{{ dir_artifacts }}/environment', dest: '/etc/profile.d/one.env' }
