---
####### Detect manifest random id name
- name: '{{ ansible_name_module }} | shell:awk | Get cluster random name'
  shell: "awk -F'[-]' '/infrastructureName/{print $2}' {{ dir_artifacts }}/data/manifests/cluster-infrastructure-02-config.yml"
  register: idrand
  ignore_errors: True

####### replace manifest random id name
- name: '{{ ansible_name_module }} | replace | s/randId/vpcName/g'
  replace:
    path: "{{ dir_artifacts_manifest }}/cluster-infrastructure-02-config.yml"
    regexp: "infrastructureName: {{ cluster_name }}-{{ idrand.stdout }}"
    replace: "infrastructureName: {{ name_cluster_vpc }}"
  ignore_errors: True

####### Itemize all manifest files
- name: '{{ ansible_name_module }} | find |  Find all manifest files'
  find:
    path: "{{ dir_artifacts }}/data"
    recurse: yes
    age: 1s
  register: manifests

####### Replace infrastructure name across all manifests
- name: '{{ ansible_name_module }} | replace | Replace infrastructureName for all files'
  replace:
    path: "{{ item.path }}"
    regexp: "{{ cluster_name }}-{{ idrand.stdout }}"
    replace: "{{ name_cluster_vpc }}"
  loop: "{{ manifests.files }}"

####### Rename region across all manifests
- name: '{{ ansible_name_module }} | replace | Replace region for all files'
  replace:
    path: "{{ item.path }}"
    regexp: "us-east-1"
    replace: "{{ cloud_region }}"
  loop: "{{ manifests.files }}"

####### Rename region across all manifests | Workaround version requires debugging and simplification
- block:
    - name: '{{ ansible_name_module }} | replace | Replace region for cluster-infrastructure-02-config.yml | TODO:FIX'
      replace:
        path: "{{ dir_artifacts }}/data/manifests/cluster-infrastructure-02-config.yml"
        regexp: "us-east-1"
        replace: "{{ cloud_region }}"
  ignore_errors: True
  always:
    - name: '{{ ansible_name_module }} | replace | Check to see if the content still exists | TODO:FIX'
      lineinfile:
        path: "{{ dir_artifacts }}/data/manifests/cluster-infrastructure-02-config.yml"
        line: us-east-1
        state: present
      check_mode: true
      register: presence
    - name: '{{ ansible_name_module }} | replace | Replace region for cluster-infrastructure-02-config.yml | TODO:FIX'
      replace:
        path: "{{ dir_artifacts }}/data/manifests/cluster-infrastructure-02-config.yml"
        regexp: "us-east-1"
        replace: "{{ cloud_region }}"
      when:  presence.changed == False

####### Add Machine API Operator Credentials
- name: '{{ ansible_name_module }} | copy | Add Machine API Operator credentials'
  copy:
    src: "{{ dir_artifacts }}/bak/openshift/"
    dest: "{{ dir_artifacts }}/data/openshift/"
  when: cluster_network_mode == 'disconnected'

####### Remove Default ingress config & non-applicable cloud credential configs
- name: '{{ ansible_name_module }} | file:state:absent | Remove {defaultIngressConfig,n/a-CloudCredConfigs'
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - "{{ dir_artifacts }}/data/openshift/99_cloud-creds-secret.yaml"
    - "{{ dir_artifacts }}/data/openshift/99_role-cloud-creds-secret-reader.yaml"
  when: cluster_network_mode == 'disconnected'
