---
####### Self Signed Certs for registry
- name: '{{ ansible_name_module }} role | manifests | openssl_privatekey | Registry Private Key'
  openssl_privatekey:
    path: "{{ dir_cluster }}/ssl/{{ cluster_domain }}.key"
    size: 4096

- name: '{{ ansible_name_module }} role | manifests | openssl_csr | Registry Certificate Signing Request'
  openssl_csr:
    path: "{{ dir_cluster }}/ssl/{{ cluster_domain }}.csr"
    privatekey_path: "{{ dir_cluster }}/ssl/{{ cluster_domain }}.key"
    common_name: "{{ cluster_domain }}"
    subject_alt_name:
      - DNS:registry.{{ cluster_domain }}
      - DNS:{{ name_domain }}
      - IP:10.0.1.1

- name: '{{ ansible_name_module }} role | manifests | openssl_certificate | Registry Self Signed Certificate'
  openssl_certificate:
    path: "{{ dir_cluster }}/ssl/{{ cluster_domain }}.crt"
    privatekey_path: "{{ dir_cluster }}/ssl/{{ cluster_domain }}.key"
    csr_path: "{{ dir_cluster }}/ssl/{{ cluster_domain }}.csr"
    provider: selfsigned
    selfsigned_not_after: "+365d"
    selfsigned_digest: "sha256"


