---
- name: ocp4-deploy | terraform-init | check TARGET_ENV environment variable
  fail:
    msg: "Environment variable TARGET_ENV not set"
  when: target_env | length < 1

- name: ocp4-deploy | task02-ignition | Initilize terraform workspaces
  shell: "cd {{ item }} && terraform init"
  with_items:
    - "{{ base_directory }}/terraform/aws-platform-base/{{ target_env }}"
    - "{{ base_directory }}/terraform/aws-platform-openshift4-registry/{{ target_env }}"
    - "{{ base_directory }}/terraform/aws-platform-openshift4-bootstrap/{{ target_env }}"
    - "{{ base_directory }}/terraform/aws-platform-openshift4-masters/{{ target_env }}"
