---
- name: ocp4-deploy | mutate-manifests | Get cluster random name
  shell: "awk -F'[-]' '/infrastructureName/{print $2}' {{ artifact_directory }}/data/manifests/cluster-infrastructure-02-config.yml"
  register: idrand
  ignore_errors: True

- name: ocp4-deploy | mutate-manifests | Replace random name with vpc name
  replace:
    path: "{{ artifact_directory }}/data/manifests/cluster-infrastructure-02-config.yml"
    regexp: "infrastructureName: {{ cluster_name }}-{{ idrand.stdout }}"
    replace: "infrastructureName: {{ vpc_name }}"
  ignore_errors: True

- name: ocp4-deploy | mutate-manifests | Find all manifest files
  find:
    path: "{{ artifact_directory }}/data"
    recurse: yes
    age: 1s
  register: manifests

- name: ocp4-deploy | mutate-manifests | Replace infrastructureName for all files
  replace:
    path: "{{ item.path }}"
    regexp: "{{ cluster_name }}-{{ idrand.stdout }}"
    replace: "{{ vpc_name }}"
  loop: "{{ manifests.files }}"

- name: ocp4-deploy | mutate-manifests | Replace region for all files
  replace:
    path: "{{ item.path }}"
    regexp: "us-east-1"
    replace: "{{ ec2_region }}"
  loop: "{{ manifests.files }}"

- block:
    - name: ocp4-deploy | mutate-manifests | Replace region for cluster-infrastructure-02-config.yml
      replace:
        path: "{{ artifact_directory }}/data/manifests/cluster-infrastructure-02-config.yml"
        regexp: "us-east-1"
        replace: "{{ ec2_region }}"
  ignore_errors: True
  always:
    - name: ocp4-deploy | mutate-manifests | Check to see if the content still exists
      lineinfile:
        path: "{{ artifact_directory }}/data/manifests/cluster-infrastructure-02-config.yml"
        line: us-east-1
        state: present
      check_mode: true
      register: presence

    - name: ocp4-deploy | mutate-manifests | Replace region for cluster-infrastructure-02-config.yml
      replace:
        path: "{{ artifact_directory }}/data/manifests/cluster-infrastructure-02-config.yml"
        regexp: "us-east-1"
        replace: "{{ ec2_region }}"
      when: "{{ presence.changed }} == False"

# only when environment is 'cloudone'
- name: ocp4-deploy | mutate-manifests | Replace label subnet name 
  replace:
    path: "{{ item.path }}"
    regexp: " {{ vpc_name }}-private-{{ ec2-region }}"
    replace: "{{ vpc_name }}-{{ subnet_postfix }}"
  loop: "{{ manifests.files }}"
  when: "{{ target_env }} == cloudone"    

- name: ocp4-deploy | mutate-manifests | Remove default ingress config & non-applicable cloud cred configs
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - "{{ artifact_directory }}/data/openshift/99_cloud-creds-secret.yaml"
    - "{{ artifact_directory }}/data/openshift/99_role-cloud-creds-secret-reader.yaml"
    
- name: ocp4-deploy | mutate-manifests | Copy Machine API Operator credentials
  copy:
    src: "{{ artifact_directory }}/bak/openshift/"
    dest: "{{ artifact_directory }}/data/openshift/"
