---
- name: '{{ ansible_name_module }} | file:absent | Purge pre-existing artifacts'
  file:
    path: '{{ dir_deploy }}/cluster/ignition'
    state: absent
- name: '{{ ansible_name_module }} | file:directory | Purge pre-existing artifacts'
  file:
    path: '{{ dir_deploy }}/cluster/ignition'
    state: directory

- name: '{{ ansible_name_module }} | copy | Load manifests into ignition directory'
  copy:
    src: "{{ dir_deploy }}/cluster/manifests/"
    dest: "{{ dir_deploy }}/cluster/ignition/"

- name: '{{ ansible_name_module }} | shell:openshift-install | Generate ignition config files'
  shell: "{{ openshift_install_binary }} create ignition-configs --dir={{ dir_deploy }}/cluster/ignition"
