---
####### Create Unified PlatformOne.tar.gz Tarball with all offline deploy requirements
- name: ocp4-deploy | task03-deploy | Purge pre-existing bundle
  file:
    path: "{{ local_home }}/PlatformOne.tar.gz"
    state: absent

- name: ocp4-deploy | task03-deploy | Archive images and artifacts
  command:
    "tar -cvzf {{ local_home }}/PlatformOne.tar.gz -C {{ local_home }} PlatformOne"
  args:
    creates: "{{ local_home }}/PlatformOne.tar.gz"

- name: ocp4-deploy | task03-deploy | Move to stateful path /root/PlatformOne/PlatformOne.tar.gz
  copy:
    src: "{{ local_home }}/PlatformOne.tar.gz"
    dest: "{{ dir_one }}/PlatformOne.tar.gz"
- name: ocp4-deploy | task03-deploy | Remove temporary build bundle
  file:
    path: "{{ local_home }}/PlatformOne.tar.gz"
    state: absent
