---
# tasks file for task03-deploy
- name: '{{ ansible_name_module }} | role | stage docker pull secret' 
  include_tasks: pull-secret.yml
- name: '{{ ansible_name_module }} | role | download openshift container images from quay.io' 
  include_tasks: mirror-to-file.yml
- name: '{{ ansible_name_module }} | role | package all dependencies' 
  include_tasks: bundle.yml
