---
####### Stage ~/.docker/config.json
- name: '{{ ansible_name_module }} | role | file | Create local docker config directory'
  file:
    path: "{{ local_home }}/.docker"
    state: directory
- name: '{{ ansible_name_module }} | role | copy | Stage RH Pull Secret to /root/.docker/config.json'
  copy:
    src: "{{ dir_artifacts }}/.docker/master.json"
    dest: "{{ local_home }}/.docker/config.json"
    
