---
- name: '{{ ansible_name_module }} | role | file | Create docker config directory'
  file:
    path: "{{ home_directory }}/.docker"
    state: directory

- name: '{{ ansible_name_module }} | role | copy | Stage RH Pull Secret to /root/.docker/config.json'
  copy:
    src: "{{ artifact_directory }}/.docker/master.json"
    dest: "{{ home_directory }}/.docker/config.json"
    
- name: '{{ ansible_name_module }} | role | block | Download OpenShift images for registry'
  block:
    - name: '{{ ansible_name_module }} | role | block | block:download | Check for file existence'
      find:
        file_type: directory
        paths: "{{ base_directory }}/mirror"
      register: files
    - name: '{{ ansible_name_module }} | role | block:download | Purge pre-existing directories'
      file:
        path: "{{ base_directory }}/mirror"
        state: absent
      when: files.examined > 0 
    - name: ocp4-deploy | task03-deploy | Create task03-deploy mirror directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "{{ base_directory }}/mirror"
        - "{{ home_directory }}/.docker"

      # Mirror Images to directory
    - name: ocp4-deploy | task03-deploy | Sync content from quay.io
      shell: |
        oc adm release mirror \
        --from=quay.io/openshift-release-dev/ocp-release:{{ ocp_version }}-x86_64 \
        --to-dir={{ base_directory }}/mirror
  # Rescue block if there are any failures in the above block
  rescue:
    - name: ocp4-deploy | task03-deploy | Remove any existing directories (if they exist)
      file:
        path: "{{ base_directory }}/mirror"
        state: absent

    - name: ocp4-deploy | task03-deploy | Create registry mirror directory
      file:
        path: "{{ base_directory }}/mirror"

    - name: ocp4-deploy | task03-deploy | Sync content from quay.io
      shell: |
        oc adm release mirror \
        --from=quay.io/openshift-release-dev/ocp-release:{{ ocp_version }}-x86_64 \
        --to-dir={{ base_directory }}/mirror
      register: mirror

- name: ocp4-deploy | task03-deploy | Archive images and artifacts
  command:
    "tar -cvzf {{ home_directory }}/PlatformOne.tar.gz -C {{ home_directory }} PlatformOne"
  args:
    creates: "{{ home_directory }}/PlatformOne.tar.gz"

